original = {1, 2, 3}
constructed = set(original)
constructed.add(4)
print(sorted(original))
print(sorted(constructed))
original.discard(99)
original.remove(2)
print(sorted(original))
copy = original.copy()
copy.add(8)
print(sorted(original))
print(sorted(copy))
original.clear()
print(len(original))
original.add(10)
print(sorted(original))
values = [1, 2]
clone = list(values)
clone.append(3)
print(values)
print(clone)
