print("Alpha".isalpha())
print("A1".isalnum())
print("123".isdigit())
print(" \t\n".isspace())
print("alpha-1".islower())
print("ALPHA1".isupper())
print("_alpha1".isidentifier())
print("1alpha".isidentifier())
print("".isalpha())
print("a\nb\r\nc\rd\ve\f".splitlines())
print("a\nb\r\nc".splitlines(True))
print("tail\n".splitlines())
