print("  alpha  ".strip())
print("xxalphaxx".strip("x"))
print("  alpha  ".lstrip())
print("xxalphaxx".rstrip("x"))
print("alphabet".startswith("pha", 2))
print("alphabet".startswith("pha", 2, 5))
print("archive.tar.gz".endswith(".tar", 0, 11))
print("archive.tar.gz".endswith((".zip", ".gz")))
print("alphabet".startswith(("zz", "al")))
print("alphabet".endswith(("bet", "zip"), 0, 8))
