/* このファイルは自動生成です。フロントエンド（HTML/CSS/JS）を1つの
 * C文字列として埋め込むことで、python_code_to_cのGUIサーバーを単一バイナリで
 * 完結させている（外部ファイルへの依存や、パス解決の問題を避けるため）。 */
#ifndef PYTHON_CODE_TO_C_GUI_HTML_H
#define PYTHON_CODE_TO_C_GUI_HTML_H

static const char PYTHON_CODE_TO_C_GUI_HTML_PART1[] =
"<!DOCTYPE html>\n"
"<html lang=\"ja\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>python_code_to_c GUI</title>\n"
"<style>\n"
"  :root {\n"
"    --bg: #1e1f26;\n"
"    --panel: #262832;\n"
"    --panel2: #2d2f3a;\n"
"    --border: #3a3d4a;\n"
"    --text: #e4e6ef;\n"
"    --muted: #9a9dae;\n"
"    --accent: #6ea8fe;\n"
"    --accent2: #4c7bd9;\n"
"    --ok: #5fd399;\n"
"    --err: #ff6b6b;\n"
"    --mono: \"SFMono-Regular\", Consolas, \"Liberation Mono\", Menlo, monospace;\n"
"  }\n"
"  * { box-sizing: border-box; }\n"
"  body {\n"
"    margin: 0;\n"
"    background: var(--bg);\n"
"    color: var(--text);\n"
"    font-family: -apple-system, \"Segoe UI\", \"Hiragino Kaku Gothic ProN\", Meiryo, sans-serif;\n"
"    height: 100vh;\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"  }\n"
"  header {\n"
"    padding: 14px 20px;\n"
"    background: var(--panel);\n"
"    border-bottom: 1px solid var(--border);\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 16px;\n"
"  }\n"
"  header h1 { font-size: 16px; margin: 0; font-weight: 600; }\n"
"  header .ver { color: var(--muted); font-size: 12px; }\n"
"  .tabs { display: flex; gap: 4px; margin-left: auto; }\n"
"  .tab {\n"
"    padding: 6px 14px;\n"
"    border-radius: 6px;\n"
"    cursor: pointer;\n"
"    font-size: 13px;\n"
"    color: var(--muted);\n"
"    border: 1px solid transparent;\n"
"  }\n"
"  .tab.active { background: var(--panel2); color: var(--text); border-color: var(--border); }\n"
"  .tab:hover { color: var(--text); }\n"
"  button.link {\n"
"    background: none; border: none; color: var(--muted); cursor: pointer; font-size: 13px;\n"
"    text-decoration: underline; padding: 0;\n"
"  }\n"
"  button.link:hover { color: var(--accent); }\n"
"  main { flex: 1; display: flex; min-height: 0; }\n"
"  .pane { flex: 1; display: flex; flex-direction: column; min-width: 0; }\n"
"  .pane + .pane { border-left: 1px solid var(--border); }\n"
"  .pane-header {\n"
"    padding: 8px 14px; font-size: 12px; color: var(--muted);\n"
"    display: flex; align-items: center; justify-content: space-between;\n"
"    background: var(--panel);\n"
"    border-bottom: 1px solid var(--border);\n"
"  }\n"
"  textarea, pre.output {\n"
"    flex: 1;\n"
"    width: 100%;\n"
"    background: var(--bg);\n"
"    color: var(--text);\n"
"    border: none;\n"
"    outline: none;\n"
"    resize: none;\n"
"    font-family: var(--mono);\n"
"    font-size: 13px;\n"
"    line-height: 1.5;\n"
"    padding: 14px;\n"
"    margin: 0;\n"
"    overflow: auto;\n"
"    white-space: pre-wrap;\n"
"    word-break: break-word;\n"
"  }\n"
"  .btnbar { display: flex; gap: 8px; }\n"
"  button.action {\n"
"    background: var(--accent2);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px 12px;\n"
"    border-radius: 5px;\n"
"    font-size: 12px;\n"
"    cursor: pointer;\n"
"  }\n"
"  button.action:hover { background: var(--accent); }\n"
"  button.action:disabled { opacity: 0.5; cursor: default; }\n"
"  button.ghost {\n"
"    background: transparent; color: var(--muted); border: 1px solid var(--border);\n"
"    padding: 5px 12px; border-radius: 5px; font-size: 12px; cursor: pointer;\n"
"  }\n"
"  button.ghost:hover { color: var(--text); border-color: var(--accent); }\n"
"  .status { font-size: 12px; padding: 2px 8px; border-radius: 4px; }\n"
"  .status.ok { color: var(--ok); }\n"
"  .status.err { color: var(--err); }\n"
"  #runPanel {\n"
"    height: 0;\n"
"    overflow: hidden;\n";

static const char PYTHON_CODE_TO_C_GUI_HTML_PART2[] =
"    border-top: 1px solid var(--border);\n"
"    background: var(--panel);\n"
"    transition: height 0.15s ease;\n"
"  }\n"
"  #runPanel.open { height: 220px; }\n"
"  #runOutput {\n"
"    height: 100%;\n"
"    margin: 0;\n"
"    padding: 12px 16px;\n"
"    font-family: var(--mono);\n"
"    font-size: 12.5px;\n"
"    white-space: pre-wrap;\n"
"    overflow: auto;\n"
"    color: var(--text);\n"
"  }\n"
"  #modal {\n"
"    display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.6);\n"
"    align-items: center; justify-content: center; z-index: 10;\n"
"  }\n"
"  #modal.open { display: flex; }\n"
"  #modalBox {\n"
"    background: var(--panel); border: 1px solid var(--border); border-radius: 8px;\n"
"    width: 720px; max-width: 90vw; max-height: 80vh; display: flex; flex-direction: column;\n"
"  }\n"
"  #modalBox header { border-radius: 8px 8px 0 0; }\n"
"  #modalBox pre {\n"
"    margin: 0; padding: 16px; overflow: auto; font-family: var(--mono); font-size: 12.5px;\n"
"    white-space: pre-wrap;\n"
"  }\n"
"  .spinner {\n"
"    display: inline-block; width: 12px; height: 12px; border: 2px solid var(--muted);\n"
"    border-top-color: var(--accent); border-radius: 50%; animation: spin 0.7s linear infinite;\n"
"  }\n"
"  @keyframes spin { to { transform: rotate(360deg); } }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>python_code_to_c</h1>\n"
"  <span class=\"ver\" id=\"verLabel\"></span>\n"
"  <div class=\"tabs\">\n"
"    <div class=\"tab active\" data-mode=\"python_code_to_c\">Python &rarr; C</div>\n"
"    <div class=\"tab\" data-mode=\"c2py\">C &rarr; Python</div>\n"
"  </div>\n"
"  <button class=\"link\" id=\"showSupported\">対応構文・機能一覧</button>\n"
"</header>\n"
"<main>\n"
"  <div class=\"pane\">\n"
"    <div class=\"pane-header\">\n"
"      <span id=\"inputLabel\">Python ソース</span>\n"
"      <div class=\"btnbar\">\n"
"        <button class=\"action\" id=\"convertBtn\">変換</button>\n"
"        <button class=\"action\" id=\"runBtn\">コンパイル＆実行</button>\n"
"      </div>\n"
"    </div>\n"
"    <textarea id=\"input\" spellcheck=\"false\">print(\"Hello from python_code_to_c!\")\n"
"\n"
"def greet(name, *, greeting=\"Hello\"):\n"
"    return greeting + \", \" + name + \"!\"\n"
"\n"
"print(greet(\"World\"))\n"
"print(greet(\"python_code_to_c\", greeting=\"Hi\"))\n"
"</textarea>\n"
"  </div>\n"
"  <div class=\"pane\">\n"
"    <div class=\"pane-header\">\n"
"      <span id=\"outputLabel\">生成されたC</span>\n"
"      <div class=\"btnbar\">\n"
"        <span class=\"status\" id=\"statusLabel\"></span>\n"
"        <button class=\"ghost\" id=\"copyBtn\">コピー</button>\n"
"      </div>\n"
"    </div>\n"
"    <pre class=\"output\" id=\"output\"></pre>\n"
"  </div>\n"
"</main>\n"
"<div id=\"runPanel\">\n"
"  <pre id=\"runOutput\"></pre>\n"
"</div>\n"
"\n"
"<div id=\"modal\">\n"
"  <div id=\"modalBox\">\n"
"    <header><span style=\"font-weight:600;font-size:14px;\">対応構文・機能一覧</span>\n"
"      <button class=\"link\" style=\"margin-left:auto\" id=\"closeModal\">閉じる</button>\n"
"    </header>\n"
"    <pre id=\"supportedText\"></pre>\n"
"  </div>\n"
"</div>\n"
"\n"
"<script>\n"
"const $ = (id) => document.getElementById(id);\n"
"let mode = \"python_code_to_c\";\n"
"\n"
"const SAMPLES = {\n"
"  python_code_to_c: `print(\"Hello from python_code_to_c!\")\n"
"\n"
"def greet(name, *, greeting=\"Hello\"):\n"
"    return greeting + \", \" + name + \"!\"\n"
"\n"
"print(greet(\"World\"))\n"
"print(greet(\"python_code_to_c\", greeting=\"Hi\"))\n"
"`,\n"
"  c2py: `#include <stdio.h>\n"
"\n"
"int add(int a, int b) {\n"
"    return a + b;\n"
"}\n"
"\n"
"int main(void) {\n";

static const char PYTHON_CODE_TO_C_GUI_HTML_PART3[] =
"    int result = add(3, 4);\n"
"    printf(\"%d\\\\n\", result);\n"
"    return 0;\n"
"}\n"
"`\n"
"};\n"
"\n"
"function setMode(m) {\n"
"  mode = m;\n"
"  document.querySelectorAll(\".tab\").forEach(t => t.classList.toggle(\"active\", t.dataset.mode === m));\n"
"  $(\"inputLabel\").textContent = m === \"python_code_to_c\" ? \"Python ソース\" : \"C ソース\";\n"
"  $(\"outputLabel\").textContent = m === \"python_code_to_c\" ? \"生成されたC\" : \"生成されたPython\";\n"
"  $(\"runBtn\").style.display = m === \"python_code_to_c\" ? \"inline-block\" : \"none\";\n"
"  $(\"input\").value = SAMPLES[m];\n"
"  $(\"output\").textContent = \"\";\n"
"  setStatus(\"\");\n"
"  closeRunPanel();\n"
"}\n"
"\n"
"document.querySelectorAll(\".tab\").forEach(t => t.addEventListener(\"click\", () => setMode(t.dataset.mode)));\n"
"\n"
"function setStatus(text, ok) {\n"
"  const el = $(\"statusLabel\");\n"
"  el.textContent = text;\n"
"  el.className = \"status\" + (ok === true ? \" ok\" : ok === false ? \" err\" : \"\");\n"
"}\n"
"\n"
"function closeRunPanel() {\n"
"  $(\"runPanel\").classList.remove(\"open\");\n"
"  $(\"runOutput\").textContent = \"\";\n"
"}\n"
"\n"
"async function convert() {\n"
"  const src = $(\"input\").value;\n"
"  $(\"convertBtn\").disabled = true;\n"
"  setStatus(\"変換中...\");\n"
"  try {\n"
"    const resp = await fetch(mode === \"python_code_to_c\" ? \"/api/python_code_to_c\" : \"/api/c2py\", {\n"
"      method: \"POST\",\n"
"      headers: { \"Content-Type\": \"text/plain; charset=utf-8\" },\n"
"      body: src\n"
"    });\n"
"    const data = await resp.json();\n"
"    if (data.ok) {\n"
"      $(\"output\").textContent = data.code;\n"
"      setStatus(\"成功\", true);\n"
"    } else {\n"
"      $(\"output\").textContent = data.error || \"変換に失敗しました\";\n"
"      setStatus(\"エラー\", false);\n"
"    }\n"
"  } catch (e) {\n"
"    $(\"output\").textContent = \"通信エラー: \" + e;\n"
"    setStatus(\"エラー\", false);\n"
"  } finally {\n"
"    $(\"convertBtn\").disabled = false;\n"
"  }\n"
"}\n"
"\n"
"async function runProgram() {\n"
"  const src = $(\"input\").value;\n"
"  $(\"runBtn\").disabled = true;\n"
"  $(\"runPanel\").classList.add(\"open\");\n"
"  $(\"runOutput\").textContent = \"コンパイル・実行中...\";\n"
"  try {\n"
"    const resp = await fetch(\"/api/run\", {\n"
"      method: \"POST\",\n"
"      headers: { \"Content-Type\": \"text/plain; charset=utf-8\" },\n"
"      body: src\n"
"    });\n"
"    const data = await resp.json();\n"
"    if (data.ok) {\n"
"      $(\"runOutput\").textContent = (data.output || \"(出力なし)\");\n"
"    } else {\n"
"      $(\"runOutput\").textContent = \"実行できませんでした:\\\\n\" + (data.error || \"\");\n"
"    }\n"
"  } catch (e) {\n"
"    $(\"runOutput\").textContent = \"通信エラー: \" + e;\n"
"  } finally {\n"
"    $(\"runBtn\").disabled = false;\n"
"  }\n"
"}\n"
"\n"
"$(\"convertBtn\").addEventListener(\"click\", convert);\n"
"$(\"runBtn\").addEventListener(\"click\", runProgram);\n"
"$(\"copyBtn\").addEventListener(\"click\", () => {\n"
"  navigator.clipboard.writeText($(\"output\").textContent).then(() => {\n"
"    const b = $(\"copyBtn\");\n"
"    const old = b.textContent;\n"
"    b.textContent = \"コピーしました\";\n"
"    setTimeout(() => b.textContent = old, 1200);\n";

static const char PYTHON_CODE_TO_C_GUI_HTML_PART4[] =
"  });\n"
"});\n"
"\n"
"$(\"showSupported\").addEventListener(\"click\", async () => {\n"
"  $(\"modal\").classList.add(\"open\");\n"
"  $(\"supportedText\").textContent = \"読み込み中...\";\n"
"  try {\n"
"    const resp = await fetch(\"/api/supported\");\n"
"    const data = await resp.json();\n"
"    $(\"supportedText\").textContent = data.text || \"\";\n"
"  } catch (e) {\n"
"    $(\"supportedText\").textContent = \"読み込みエラー: \" + e;\n"
"  }\n"
"});\n"
"$(\"closeModal\").addEventListener(\"click\", () => $(\"modal\").classList.remove(\"open\"));\n"
"$(\"modal\").addEventListener(\"click\", (e) => { if (e.target.id === \"modal\") $(\"modal\").classList.remove(\"open\"); });\n"
"\n"
"fetch(\"/api/version\").then(r => r.json()).then(d => { $(\"verLabel\").textContent = d.version || \"\"; }).catch(() => {});\n"
"\n"
"setMode(\"python_code_to_c\");\n"
"</script>\n"
"</body>\n"
"</html>\n"
"\n"
;

#endif

